version: '3'

services:
  # ui:
  #   image: zedcloud
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./:/app
  #     - ./node_modules:/app/node_modules

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   volumes:
  #     - mongodb_data:/data/db
  aria2:
    image: p3terx/aria2-pro # Replace with the actual Aria2 image name
    ports:
      - "6800:6800" # Map Aria2's port to the host
    volumes:
      - ${PWD}/downloads:/downloads
volumes:
  aria2-downloads:
    # Define the named volume for Aria2 downloads
    # mongodb_data:


